version: "3.4"
services:
  lianmi-chatservice:
    image: lianmi/chatservice:0.1
    build: ./chatservice
    container_name: lianmi-chatservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/chatservice.log:/tmp/chatservice.log
      - /root/developments/lianmi/work/logs/chatservice.log:/tmp/chatservice.log

  lianmi-orderservice:
    image: lianmi/orderservice:0.1
    build: ./orderservice
    container_name: lianmi-orderservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/orderservice.log:/tmp/orderservice.log
      - /root/developments/lianmi/work/logs/orderservice.log:/tmp/orderservice.log

  lianmi-walletservice:
    image: lianmi/walletservice:0.1
    build: ./walletservice
    container_name: lianmi-walletservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/walletservice.log:/tmp/walletservice.log
      - /root/developments/lianmi/work/logs/walletservice.log:/tmp/walletservice.log
      - /store/blockchain/lianmichain/node1:/etc/node

  lianmi-dispatcher:
    image: lianmi/dispatcher:0.1
    build: ./dispatcher
    container_name: lianmi-dispatcher 
    restart: unless-stopped
    ports:
      - 28080:28080    
    volumes:
      # - ${LOG_DIR}/dispatcher.log:/tmp/dispatcher.log
      - /root/developments/lianmi/work/logs/dispatcher.log:/tmp/dispatcher.log
      - /root/developments/lianmi/work/basic/mosquitto/ca:/etc/ca
      
  # lianmi-admin-server:
  #   image: lianmi/admin-server:0.1
  #   container_name: lianmi-admin-server
  #   restart: unless-stopped
  #   ports:
  #     - '127.0.0.1:28088:8888'
  #   volumes:
  #    - /root/developments/lianmi/work/logs/lianmi-admin-server.log:/app/latest_log
  #    - ./lianmi-admin-server/config.yaml:/app/config.yaml

networks:
  default:
    # driver: bridge
    external:
      name: br-lianmi # Create using "docker network create br-lianmi" before run.
