version: "3.4"
services:
  lianmi-authservice:
    image: lianmi/authservice:0.1
    build: ./authservice
    container_name: lianmi-authservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/authservice.log:/tmp/authservice.log
      - /root/developments/lianmi/work/logs/authservice.log:/tmp/authservice.log
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: lianmi.lm-cloud.authservice

  lianmi-chatservice:
    image: lianmi/chatservice:0.1
    build: ./chatservice
    container_name: lianmi-chatservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/chatservice.log:/tmp/chatservice.log
      - /root/developments/lianmi/work/logs/chatservice.log:/tmp/chatservice.log
      - /root/developments/lianmi/work/basic/mosquitto/ca:/ca
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: lianmi.lm-cloud.chatservice

  lianmi-orderservice:
    image: lianmi/orderservice:0.1
    build: ./orderservice
    container_name: lianmi-orderservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/orderservice.log:/tmp/orderservice.log
      - /root/developments/lianmi/work/logs/orderservice.log:/tmp/orderservice.log
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: lianmi.lm-cloud.orderservice

  lianmi-walletservice:
    image: lianmi/walletservice:0.1
    build: ./walletservice
    container_name: lianmi-walletservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/walletservice.log:/tmp/walletservice.log
      - /root/developments/lianmi/work/logs/walletservice.log:/tmp/walletservice.log
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: lianmi.lm-cloud.walletservice

  lianmi-dispatcher:
    image: lianmi/dispatcher:0.1
    build: ./dispatcher
    container_name: lianmi-dispatcher 
    restart: unless-stopped
    ports:
      - 28080:28080    
    volumes:
      # - ${LOG_DIR}/dispatcher.log:/tmp/dispatcher.log
      - /root/developments/lianmi/work/logs/dispatcher.log:/tmp/dispatcher.log
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: lianmi.lm-cloud.dispatcher

networks:
  default:
    # driver: bridge
    external:
      name: br-lianmi # Create using "docker network create br-lianmi" before run.