version: "3.4"
services:
  lianmi-chatservice:
    image: lianmi/chatservice:0.1
    build: ./chatservice
    container_name: lianmi-chatservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/chatservice.log:/tmp/chatservice.log
      - /root/developments/lianmi/work/logs/chatservice.log:/tmp/chatservice.log

  lianmi-orderservice:
    image: lianmi/orderservice:0.1
    build: ./orderservice
    container_name: lianmi-orderservice
    restart: unless-stopped
    volumes:
      # - ${LOG_DIR}/orderservice.log:/tmp/orderservice.log
      - /root/developments/lianmi/work/logs/orderservice.log:/tmp/orderservice.log

  lianmi-dispatcher:
    image: lianmi/dispatcher:0.1
    build: ./dispatcher
    container_name: lianmi-dispatcher 
    restart: unless-stopped
    ports:
      - 28080:28080
    volumes:
      # - ${LOG_DIR}/dispatcher.log:/tmp/dispatcher.log
      - /root/developments/lianmi/work/logs/dispatcher.log:/tmp/dispatcher.log
      - /root/developments/lianmi/work/basic/mosquitto/ca:/etc/ca
      - /root/developments/lianmi/work/basic/upload:/tmp/upload
      
networks:
  default:
    # driver: bridge
    external:
      name: br-lianmi # Create using "docker network create br-lianmi" before run.
