// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/friends/CancelWatching.proto

package friends

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//取消关注商户
//对某商户发起取消关注指令
//API类型-API
type CancelWatchingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//商户账号
	//是否必填-是
	BusinessUsername string `protobuf:"bytes,1,opt,name=businessUsername,proto3" json:"businessUsername,omitempty"`
	//附言
	//是否必填-否
	Ps string `protobuf:"bytes,2,opt,name=ps,proto3" json:"ps,omitempty"`
}

func (x *CancelWatchingReq) Reset() {
	*x = CancelWatchingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friends_CancelWatching_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelWatchingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWatchingReq) ProtoMessage() {}

func (x *CancelWatchingReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friends_CancelWatching_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWatchingReq.ProtoReflect.Descriptor instead.
func (*CancelWatchingReq) Descriptor() ([]byte, []int) {
	return file_api_proto_friends_CancelWatching_proto_rawDescGZIP(), []int{0}
}

func (x *CancelWatchingReq) GetBusinessUsername() string {
	if x != nil {
		return x.BusinessUsername
	}
	return ""
}

func (x *CancelWatchingReq) GetPs() string {
	if x != nil {
		return x.Ps
	}
	return ""
}

type CancelWatchingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOK bool `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
}

func (x *CancelWatchingRsp) Reset() {
	*x = CancelWatchingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friends_CancelWatching_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelWatchingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWatchingRsp) ProtoMessage() {}

func (x *CancelWatchingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friends_CancelWatching_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWatchingRsp.ProtoReflect.Descriptor instead.
func (*CancelWatchingRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_friends_CancelWatching_proto_rawDescGZIP(), []int{1}
}

func (x *CancelWatchingRsp) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

var File_api_proto_friends_CancelWatching_proto protoreflect.FileDescriptor

var file_api_proto_friends_CancelWatching_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x2f, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x22, 0x4f, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x10, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x70, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_proto_friends_CancelWatching_proto_rawDescOnce sync.Once
	file_api_proto_friends_CancelWatching_proto_rawDescData = file_api_proto_friends_CancelWatching_proto_rawDesc
)

func file_api_proto_friends_CancelWatching_proto_rawDescGZIP() []byte {
	file_api_proto_friends_CancelWatching_proto_rawDescOnce.Do(func() {
		file_api_proto_friends_CancelWatching_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_friends_CancelWatching_proto_rawDescData)
	})
	return file_api_proto_friends_CancelWatching_proto_rawDescData
}

var file_api_proto_friends_CancelWatching_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_friends_CancelWatching_proto_goTypes = []interface{}{
	(*CancelWatchingReq)(nil), // 0: cloud.lianmi.im.friends.CancelWatchingReq
	(*CancelWatchingRsp)(nil), // 1: cloud.lianmi.im.friends.CancelWatchingRsp
}
var file_api_proto_friends_CancelWatching_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_friends_CancelWatching_proto_init() }
func file_api_proto_friends_CancelWatching_proto_init() {
	if File_api_proto_friends_CancelWatching_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_friends_CancelWatching_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelWatchingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friends_CancelWatching_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelWatchingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_friends_CancelWatching_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_friends_CancelWatching_proto_goTypes,
		DependencyIndexes: file_api_proto_friends_CancelWatching_proto_depIdxs,
		MessageInfos:      file_api_proto_friends_CancelWatching_proto_msgTypes,
	}.Build()
	File_api_proto_friends_CancelWatching_proto = out.File
	file_api_proto_friends_CancelWatching_proto_rawDesc = nil
	file_api_proto_friends_CancelWatching_proto_goTypes = nil
	file_api_proto_friends_CancelWatching_proto_depIdxs = nil
}
