// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/wallet/Deposit.proto

package wallet

import (
	proto "github.com/golang/protobuf/proto"
	global "github.com/lianmi/servers/api/proto/global"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DepositReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户选择的支付接口类型
	PaymentType global.ThirdPartyPaymentType `protobuf:"varint,1,opt,name=paymentType,proto3,enum=cloud.lianmi.im.global.ThirdPartyPaymentType" json:"paymentType,omitempty"`
	//充值金额，人民币格式
	RechargeAmount float64 `protobuf:"fixed64,2,opt,name=rechargeAmount,proto3" json:"rechargeAmount,omitempty"`
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_Deposit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_Deposit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_Deposit_proto_rawDescGZIP(), []int{0}
}

func (x *DepositReq) GetPaymentType() global.ThirdPartyPaymentType {
	if x != nil {
		return x.PaymentType
	}
	return global.ThirdPartyPaymentType_TPPT_Undefined
}

func (x *DepositReq) GetRechargeAmount() float64 {
	if x != nil {
		return x.RechargeAmount
	}
	return 0
}

type DepositRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 区块高度
	BlockNumber uint64 `protobuf:"fixed64,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	// 交易哈希hex
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	//充值之后的连米币余额
	AmountLNMC uint64 `protobuf:"fixed64,3,opt,name=amountLNMC,proto3" json:"amountLNMC,omitempty"`
	//打包完成时间
	Time uint64 `protobuf:"fixed64,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *DepositRsp) Reset() {
	*x = DepositRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_Deposit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRsp) ProtoMessage() {}

func (x *DepositRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_Deposit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRsp.ProtoReflect.Descriptor instead.
func (*DepositRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_Deposit_proto_rawDescGZIP(), []int{1}
}

func (x *DepositRsp) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *DepositRsp) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DepositRsp) GetAmountLNMC() uint64 {
	if x != nil {
		return x.AmountLNMC
	}
	return 0
}

func (x *DepositRsp) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_api_proto_wallet_Deposit_proto protoreflect.FileDescriptor

var file_api_proto_wallet_Deposit_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2f, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69,
	0x6d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x4f, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x68, 0x61,
	0x72, 0x67, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0e, 0x72, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x76, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a,
	0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x06, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x4e, 0x4d,
	0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4c,
	0x4e, 0x4d, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_wallet_Deposit_proto_rawDescOnce sync.Once
	file_api_proto_wallet_Deposit_proto_rawDescData = file_api_proto_wallet_Deposit_proto_rawDesc
)

func file_api_proto_wallet_Deposit_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_Deposit_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_Deposit_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_wallet_Deposit_proto_rawDescData)
	})
	return file_api_proto_wallet_Deposit_proto_rawDescData
}

var file_api_proto_wallet_Deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_wallet_Deposit_proto_goTypes = []interface{}{
	(*DepositReq)(nil),                // 0: cloud.lianmi.im.wallet.DepositReq
	(*DepositRsp)(nil),                // 1: cloud.lianmi.im.wallet.DepositRsp
	(global.ThirdPartyPaymentType)(0), // 2: cloud.lianmi.im.global.ThirdPartyPaymentType
}
var file_api_proto_wallet_Deposit_proto_depIdxs = []int32{
	2, // 0: cloud.lianmi.im.wallet.DepositReq.paymentType:type_name -> cloud.lianmi.im.global.ThirdPartyPaymentType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_Deposit_proto_init() }
func file_api_proto_wallet_Deposit_proto_init() {
	if File_api_proto_wallet_Deposit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_wallet_Deposit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_wallet_Deposit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_wallet_Deposit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_wallet_Deposit_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_Deposit_proto_depIdxs,
		MessageInfos:      file_api_proto_wallet_Deposit_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_Deposit_proto = out.File
	file_api_proto_wallet_Deposit_proto_rawDesc = nil
	file_api_proto_wallet_Deposit_proto_goTypes = nil
	file_api_proto_wallet_Deposit_proto_depIdxs = nil
}
