// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/wallet/PreTransfer.proto

package wallet

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//裸交易结构体
type RawDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//nonce
	Nonce uint64 `protobuf:"fixed64,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// gas价格
	GasPrice uint64 `protobuf:"fixed64,2,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// 最低gas
	GasLimit uint64 `protobuf:"fixed64,3,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	//链id
	ChainID uint64 `protobuf:"fixed64,4,opt,name=chainID,proto3" json:"chainID,omitempty"`
	// 交易数据
	Txdata []byte `protobuf:"bytes,5,opt,name=txdata,proto3" json:"txdata,omitempty"`
	//收款者地址
	ToWalletAddress string `protobuf:"bytes,6,opt,name=toWalletAddress,proto3" json:"toWalletAddress,omitempty"`
	//要转账的代币数量
	Value uint64 `protobuf:"fixed64,7,opt,name=value,proto3" json:"value,omitempty"`
	//交易哈希
	TxHash string `protobuf:"bytes,8,opt,name=txHash,proto3" json:"txHash,omitempty"`
	//发币智能合约地址
	ContractAddress string `protobuf:"bytes,9,opt,name=ContractAddress,proto3" json:"ContractAddress,omitempty"`
}

func (x *RawDesc) Reset() {
	*x = RawDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_PreTransfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDesc) ProtoMessage() {}

func (x *RawDesc) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_PreTransfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDesc.ProtoReflect.Descriptor instead.
func (*RawDesc) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_PreTransfer_proto_rawDescGZIP(), []int{0}
}

func (x *RawDesc) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *RawDesc) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *RawDesc) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *RawDesc) GetChainID() uint64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *RawDesc) GetTxdata() []byte {
	if x != nil {
		return x.Txdata
	}
	return nil
}

func (x *RawDesc) GetToWalletAddress() string {
	if x != nil {
		return x.ToWalletAddress
	}
	return ""
}

func (x *RawDesc) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RawDesc) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *RawDesc) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type PreTransferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//订单ID（ 非空的时候，targetUserName 必须是空 两者选一）
	OrderID string `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	//收款方的用户账号（非空的时候，orderID必须是空 两者选一）
	TargetUserName string `protobuf:"bytes,2,opt,name=targetUserName,proto3" json:"targetUserName,omitempty"`
	//金额(人民币格式)， 服务端要转换为代币格式
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	//附言
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PreTransferReq) Reset() {
	*x = PreTransferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_PreTransfer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreTransferReq) ProtoMessage() {}

func (x *PreTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_PreTransfer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreTransferReq.ProtoReflect.Descriptor instead.
func (*PreTransferReq) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_PreTransfer_proto_rawDescGZIP(), []int{1}
}

func (x *PreTransferReq) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PreTransferReq) GetTargetUserName() string {
	if x != nil {
		return x.TargetUserName
	}
	return ""
}

func (x *PreTransferReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PreTransferReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PreTransferRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//向收款方转账的裸交易结构体
	RawDescToTarget *RawDesc `protobuf:"bytes,1,opt,name=rawDescToTarget,proto3" json:"rawDescToTarget,omitempty"`
	//时间
	Time uint64 `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *PreTransferRsp) Reset() {
	*x = PreTransferRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_PreTransfer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreTransferRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreTransferRsp) ProtoMessage() {}

func (x *PreTransferRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_PreTransfer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreTransferRsp.ProtoReflect.Descriptor instead.
func (*PreTransferRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_PreTransfer_proto_rawDescGZIP(), []int{2}
}

func (x *PreTransferRsp) GetRawDescToTarget() *RawDesc {
	if x != nil {
		return x.RawDescToTarget
	}
	return nil
}

func (x *PreTransferRsp) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_api_proto_wallet_PreTransfer_proto protoreflect.FileDescriptor

var file_api_proto_wallet_PreTransfer_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2f, 0x50, 0x72, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e,
	0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x8b, 0x02, 0x0a,
	0x07, 0x52, 0x61, 0x77, 0x44, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06,
	0x52, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61,
	0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x67, 0x61,
	0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x74, 0x78, 0x64, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x6f, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x74, 0x6f, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x50,
	0x72, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x6f, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x52, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x0f, 0x72, 0x61, 0x77, 0x44, 0x65, 0x73, 0x63, 0x54, 0x6f,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x52, 0x61, 0x77, 0x44, 0x65, 0x73, 0x63, 0x52, 0x0f, 0x72,
	0x61, 0x77, 0x44, 0x65, 0x73, 0x63, 0x54, 0x6f, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_wallet_PreTransfer_proto_rawDescOnce sync.Once
	file_api_proto_wallet_PreTransfer_proto_rawDescData = file_api_proto_wallet_PreTransfer_proto_rawDesc
)

func file_api_proto_wallet_PreTransfer_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_PreTransfer_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_PreTransfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_wallet_PreTransfer_proto_rawDescData)
	})
	return file_api_proto_wallet_PreTransfer_proto_rawDescData
}

var file_api_proto_wallet_PreTransfer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_wallet_PreTransfer_proto_goTypes = []interface{}{
	(*RawDesc)(nil),        // 0: cloud.lianmi.im.wallet.RawDesc
	(*PreTransferReq)(nil), // 1: cloud.lianmi.im.wallet.PreTransferReq
	(*PreTransferRsp)(nil), // 2: cloud.lianmi.im.wallet.PreTransferRsp
}
var file_api_proto_wallet_PreTransfer_proto_depIdxs = []int32{
	0, // 0: cloud.lianmi.im.wallet.PreTransferRsp.rawDescToTarget:type_name -> cloud.lianmi.im.wallet.RawDesc
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_PreTransfer_proto_init() }
func file_api_proto_wallet_PreTransfer_proto_init() {
	if File_api_proto_wallet_PreTransfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_wallet_PreTransfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_wallet_PreTransfer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreTransferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_wallet_PreTransfer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreTransferRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_wallet_PreTransfer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_wallet_PreTransfer_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_PreTransfer_proto_depIdxs,
		MessageInfos:      file_api_proto_wallet_PreTransfer_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_PreTransfer_proto = out.File
	file_api_proto_wallet_PreTransfer_proto_rawDesc = nil
	file_api_proto_wallet_PreTransfer_proto_goTypes = nil
	file_api_proto_wallet_PreTransfer_proto_depIdxs = nil
}
