// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/wallet/PreWithDraw.proto

package wallet

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PreWithDrawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 提现金额
	Amount float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	//手机短信验证码
	Smscode string `protobuf:"bytes,2,opt,name=smscode,proto3" json:"smscode,omitempty"`
	//银行名称
	Bank string `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	//银行卡号
	BankCard string `protobuf:"bytes,4,opt,name=bankCard,proto3" json:"bankCard,omitempty"`
	//银行开卡人姓名
	CardOwner string `protobuf:"bytes,5,opt,name=cardOwner,proto3" json:"cardOwner,omitempty"`
}

func (x *PreWithDrawReq) Reset() {
	*x = PreWithDrawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_PreWithDraw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreWithDrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreWithDrawReq) ProtoMessage() {}

func (x *PreWithDrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_PreWithDraw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreWithDrawReq.ProtoReflect.Descriptor instead.
func (*PreWithDrawReq) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_PreWithDraw_proto_rawDescGZIP(), []int{0}
}

func (x *PreWithDrawReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PreWithDrawReq) GetSmscode() string {
	if x != nil {
		return x.Smscode
	}
	return ""
}

func (x *PreWithDrawReq) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *PreWithDrawReq) GetBankCard() string {
	if x != nil {
		return x.BankCard
	}
	return ""
}

func (x *PreWithDrawReq) GetCardOwner() string {
	if x != nil {
		return x.CardOwner
	}
	return ""
}

type PreWithDrawRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//提现单编号，UUID
	WithdrawUUID string `protobuf:"bytes,1,opt,name=withdrawUUID,proto3" json:"withdrawUUID,omitempty"`
	//向平台方转账的裸交易结构体
	RawDescToPlatform *RawDesc `protobuf:"bytes,2,opt,name=rawDescToPlatform,proto3" json:"rawDescToPlatform,omitempty"`
	//时间
	Time uint64 `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *PreWithDrawRsp) Reset() {
	*x = PreWithDrawRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_PreWithDraw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreWithDrawRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreWithDrawRsp) ProtoMessage() {}

func (x *PreWithDrawRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_PreWithDraw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreWithDrawRsp.ProtoReflect.Descriptor instead.
func (*PreWithDrawRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_PreWithDraw_proto_rawDescGZIP(), []int{1}
}

func (x *PreWithDrawRsp) GetWithdrawUUID() string {
	if x != nil {
		return x.WithdrawUUID
	}
	return ""
}

func (x *PreWithDrawRsp) GetRawDescToPlatform() *RawDesc {
	if x != nil {
		return x.RawDescToPlatform
	}
	return nil
}

func (x *PreWithDrawRsp) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_api_proto_wallet_PreWithDraw_proto protoreflect.FileDescriptor

var file_api_proto_wallet_PreWithDraw_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2f, 0x50, 0x72, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x72, 0x61, 0x77, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e,
	0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x22, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x50,
	0x72, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x90, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x72, 0x61, 0x77,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x6d, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6d,
	0x73, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e,
	0x6b, 0x43, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e,
	0x6b, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44,
	0x72, 0x61, 0x77, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x55, 0x55, 0x49, 0x44, 0x12, 0x4d, 0x0a, 0x11, 0x72, 0x61,
	0x77, 0x44, 0x65, 0x73, 0x63, 0x54, 0x6f, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69,
	0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x52,
	0x61, 0x77, 0x44, 0x65, 0x73, 0x63, 0x52, 0x11, 0x72, 0x61, 0x77, 0x44, 0x65, 0x73, 0x63, 0x54,
	0x6f, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e,
	0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_proto_wallet_PreWithDraw_proto_rawDescOnce sync.Once
	file_api_proto_wallet_PreWithDraw_proto_rawDescData = file_api_proto_wallet_PreWithDraw_proto_rawDesc
)

func file_api_proto_wallet_PreWithDraw_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_PreWithDraw_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_PreWithDraw_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_wallet_PreWithDraw_proto_rawDescData)
	})
	return file_api_proto_wallet_PreWithDraw_proto_rawDescData
}

var file_api_proto_wallet_PreWithDraw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_wallet_PreWithDraw_proto_goTypes = []interface{}{
	(*PreWithDrawReq)(nil), // 0: cloud.lianmi.im.wallet.PreWithDrawReq
	(*PreWithDrawRsp)(nil), // 1: cloud.lianmi.im.wallet.PreWithDrawRsp
	(*RawDesc)(nil),        // 2: cloud.lianmi.im.wallet.RawDesc
}
var file_api_proto_wallet_PreWithDraw_proto_depIdxs = []int32{
	2, // 0: cloud.lianmi.im.wallet.PreWithDrawRsp.rawDescToPlatform:type_name -> cloud.lianmi.im.wallet.RawDesc
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_PreWithDraw_proto_init() }
func file_api_proto_wallet_PreWithDraw_proto_init() {
	if File_api_proto_wallet_PreWithDraw_proto != nil {
		return
	}
	file_api_proto_wallet_PreTransfer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_wallet_PreWithDraw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreWithDrawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_wallet_PreWithDraw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreWithDrawRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_wallet_PreWithDraw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_wallet_PreWithDraw_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_PreWithDraw_proto_depIdxs,
		MessageInfos:      file_api_proto_wallet_PreWithDraw_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_PreWithDraw_proto = out.File
	file_api_proto_wallet_PreWithDraw_proto_rawDesc = nil
	file_api_proto_wallet_PreWithDraw_proto_goTypes = nil
	file_api_proto_wallet_PreWithDraw_proto_depIdxs = nil
}
