// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/wallet/SyncTransferHistory.proto

package wallet

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SyncTransferHistoryPageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//开始时间
	StartAt uint64 `protobuf:"fixed64,1,opt,name=startAt,proto3" json:"startAt,omitempty"`
	//结束时间
	EndAt uint64 `protobuf:"fixed64,2,opt,name=endAt,proto3" json:"endAt,omitempty"`
	//页数,第几页
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	//每页记录数量
	PageSize int32 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *SyncTransferHistoryPageReq) Reset() {
	*x = SyncTransferHistoryPageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_SyncTransferHistory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncTransferHistoryPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTransferHistoryPageReq) ProtoMessage() {}

func (x *SyncTransferHistoryPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_SyncTransferHistory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTransferHistoryPageReq.ProtoReflect.Descriptor instead.
func (*SyncTransferHistoryPageReq) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_SyncTransferHistory_proto_rawDescGZIP(), []int{0}
}

func (x *SyncTransferHistoryPageReq) GetStartAt() uint64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *SyncTransferHistoryPageReq) GetEndAt() uint64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *SyncTransferHistoryPageReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SyncTransferHistoryPageReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SyncTransferHistoryPageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//转账记录列表
	Transfers []*Transfer `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	//按请求参数的pageSize计算出来的总页数
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *SyncTransferHistoryPageRsp) Reset() {
	*x = SyncTransferHistoryPageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_SyncTransferHistory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncTransferHistoryPageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTransferHistoryPageRsp) ProtoMessage() {}

func (x *SyncTransferHistoryPageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_SyncTransferHistory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTransferHistoryPageRsp.ProtoReflect.Descriptor instead.
func (*SyncTransferHistoryPageRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_SyncTransferHistory_proto_rawDescGZIP(), []int{1}
}

func (x *SyncTransferHistoryPageRsp) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *SyncTransferHistoryPageRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_proto_wallet_SyncTransferHistory_proto protoreflect.FileDescriptor

var file_api_proto_wallet_SyncTransferHistory_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2f, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x1a, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x06, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6e, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x72, 0x0a, 0x1a, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x3e, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_wallet_SyncTransferHistory_proto_rawDescOnce sync.Once
	file_api_proto_wallet_SyncTransferHistory_proto_rawDescData = file_api_proto_wallet_SyncTransferHistory_proto_rawDesc
)

func file_api_proto_wallet_SyncTransferHistory_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_SyncTransferHistory_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_SyncTransferHistory_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_wallet_SyncTransferHistory_proto_rawDescData)
	})
	return file_api_proto_wallet_SyncTransferHistory_proto_rawDescData
}

var file_api_proto_wallet_SyncTransferHistory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_wallet_SyncTransferHistory_proto_goTypes = []interface{}{
	(*SyncTransferHistoryPageReq)(nil), // 0: cloud.lianmi.im.wallet.SyncTransferHistoryPageReq
	(*SyncTransferHistoryPageRsp)(nil), // 1: cloud.lianmi.im.wallet.SyncTransferHistoryPageRsp
	(*Transfer)(nil),                   // 2: cloud.lianmi.im.wallet.Transfer
}
var file_api_proto_wallet_SyncTransferHistory_proto_depIdxs = []int32{
	2, // 0: cloud.lianmi.im.wallet.SyncTransferHistoryPageRsp.transfers:type_name -> cloud.lianmi.im.wallet.Transfer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_SyncTransferHistory_proto_init() }
func file_api_proto_wallet_SyncTransferHistory_proto_init() {
	if File_api_proto_wallet_SyncTransferHistory_proto != nil {
		return
	}
	file_api_proto_wallet_Wallet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_wallet_SyncTransferHistory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncTransferHistoryPageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_wallet_SyncTransferHistory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncTransferHistoryPageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_wallet_SyncTransferHistory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_wallet_SyncTransferHistory_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_SyncTransferHistory_proto_depIdxs,
		MessageInfos:      file_api_proto_wallet_SyncTransferHistory_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_SyncTransferHistory_proto = out.File
	file_api_proto_wallet_SyncTransferHistory_proto_rawDesc = nil
	file_api_proto_wallet_SyncTransferHistory_proto_goTypes = nil
	file_api_proto_wallet_SyncTransferHistory_proto_depIdxs = nil
}
