// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/wallet/UserSignIn.proto

package wallet

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserSignInReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserSignInReq) Reset() {
	*x = UserSignInReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_UserSignIn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInReq) ProtoMessage() {}

func (x *UserSignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_UserSignIn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInReq.ProtoReflect.Descriptor instead.
func (*UserSignInReq) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_UserSignIn_proto_rawDescGZIP(), []int{0}
}

type UserSignInRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//最新签到次数
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	//总签到数
	TotalSignIn uint64 `protobuf:"fixed64,2,opt,name=totalSignIn,proto3" json:"totalSignIn,omitempty"`
}

func (x *UserSignInRsp) Reset() {
	*x = UserSignInRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_UserSignIn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInRsp) ProtoMessage() {}

func (x *UserSignInRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_UserSignIn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInRsp.ProtoReflect.Descriptor instead.
func (*UserSignInRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_UserSignIn_proto_rawDescGZIP(), []int{1}
}

func (x *UserSignInRsp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UserSignInRsp) GetTotalSignIn() uint64 {
	if x != nil {
		return x.TotalSignIn
	}
	return 0
}

var File_api_proto_wallet_UserSignIn_proto protoreflect.FileDescriptor

var file_api_proto_wallet_UserSignIn_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x47, 0x0a, 0x0d,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e,
	0x49, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_wallet_UserSignIn_proto_rawDescOnce sync.Once
	file_api_proto_wallet_UserSignIn_proto_rawDescData = file_api_proto_wallet_UserSignIn_proto_rawDesc
)

func file_api_proto_wallet_UserSignIn_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_UserSignIn_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_UserSignIn_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_wallet_UserSignIn_proto_rawDescData)
	})
	return file_api_proto_wallet_UserSignIn_proto_rawDescData
}

var file_api_proto_wallet_UserSignIn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_wallet_UserSignIn_proto_goTypes = []interface{}{
	(*UserSignInReq)(nil), // 0: cloud.lianmi.im.wallet.UserSignInReq
	(*UserSignInRsp)(nil), // 1: cloud.lianmi.im.wallet.UserSignInRsp
}
var file_api_proto_wallet_UserSignIn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_UserSignIn_proto_init() }
func file_api_proto_wallet_UserSignIn_proto_init() {
	if File_api_proto_wallet_UserSignIn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_wallet_UserSignIn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_wallet_UserSignIn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_wallet_UserSignIn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_wallet_UserSignIn_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_UserSignIn_proto_depIdxs,
		MessageInfos:      file_api_proto_wallet_UserSignIn_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_UserSignIn_proto = out.File
	file_api_proto_wallet_UserSignIn_proto_rawDesc = nil
	file_api_proto_wallet_UserSignIn_proto_goTypes = nil
	file_api_proto_wallet_UserSignIn_proto_depIdxs = nil
}
