// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/wallet/WithDraw.proto

package wallet

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WithDrawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//提现单编号，UUID
	WithdrawUUID string `protobuf:"bytes,1,opt,name=withdrawUUID,proto3" json:"withdrawUUID,omitempty"`
	//签名后的转账到平台方的Tx交易数据
	SignedTxToPlatform string `protobuf:"bytes,2,opt,name=signedTxToPlatform,proto3" json:"signedTxToPlatform,omitempty"`
}

func (x *WithDrawReq) Reset() {
	*x = WithDrawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_WithDraw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithDrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithDrawReq) ProtoMessage() {}

func (x *WithDrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_WithDraw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithDrawReq.ProtoReflect.Descriptor instead.
func (*WithDrawReq) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_WithDraw_proto_rawDescGZIP(), []int{0}
}

func (x *WithDrawReq) GetWithdrawUUID() string {
	if x != nil {
		return x.WithdrawUUID
	}
	return ""
}

func (x *WithDrawReq) GetSignedTxToPlatform() string {
	if x != nil {
		return x.SignedTxToPlatform
	}
	return ""
}

type WithDrawRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 区块高度
	BlockNumber uint64 `protobuf:"fixed64,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	// 交易哈希hex
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	//充值之后的连米币余额
	BalanceLNMC uint64 `protobuf:"fixed64,3,opt,name=balanceLNMC,proto3" json:"balanceLNMC,omitempty"`
	//打包完成时间
	Time uint64 `protobuf:"fixed64,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *WithDrawRsp) Reset() {
	*x = WithDrawRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_wallet_WithDraw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithDrawRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithDrawRsp) ProtoMessage() {}

func (x *WithDrawRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_WithDraw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithDrawRsp.ProtoReflect.Descriptor instead.
func (*WithDrawRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_WithDraw_proto_rawDescGZIP(), []int{1}
}

func (x *WithDrawRsp) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *WithDrawRsp) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *WithDrawRsp) GetBalanceLNMC() uint64 {
	if x != nil {
		return x.BalanceLNMC
	}
	return 0
}

func (x *WithDrawRsp) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_api_proto_wallet_WithDraw_proto protoreflect.FileDescriptor

var file_api_proto_wallet_WithDraw_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2f, 0x57, 0x69, 0x74, 0x68, 0x44, 0x72, 0x61, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e,
	0x69, 0x6d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x61, 0x0a, 0x0b, 0x57, 0x69, 0x74,
	0x68, 0x44, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x77, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x55, 0x55, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x12,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x78, 0x54, 0x6f, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x54, 0x78, 0x54, 0x6f, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x79, 0x0a, 0x0b,
	0x57, 0x69, 0x74, 0x68, 0x44, 0x72, 0x61, 0x77, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06,
	0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x4e, 0x4d, 0x43,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0b, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c,
	0x4e, 0x4d, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_wallet_WithDraw_proto_rawDescOnce sync.Once
	file_api_proto_wallet_WithDraw_proto_rawDescData = file_api_proto_wallet_WithDraw_proto_rawDesc
)

func file_api_proto_wallet_WithDraw_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_WithDraw_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_WithDraw_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_wallet_WithDraw_proto_rawDescData)
	})
	return file_api_proto_wallet_WithDraw_proto_rawDescData
}

var file_api_proto_wallet_WithDraw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_wallet_WithDraw_proto_goTypes = []interface{}{
	(*WithDrawReq)(nil), // 0: cloud.lianmi.im.wallet.WithDrawReq
	(*WithDrawRsp)(nil), // 1: cloud.lianmi.im.wallet.WithDrawRsp
}
var file_api_proto_wallet_WithDraw_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_WithDraw_proto_init() }
func file_api_proto_wallet_WithDraw_proto_init() {
	if File_api_proto_wallet_WithDraw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_wallet_WithDraw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithDrawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_wallet_WithDraw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithDrawRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_wallet_WithDraw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_wallet_WithDraw_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_WithDraw_proto_depIdxs,
		MessageInfos:      file_api_proto_wallet_WithDraw_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_WithDraw_proto = out.File
	file_api_proto_wallet_WithDraw_proto_rawDesc = nil
	file_api_proto_wallet_WithDraw_proto_goTypes = nil
	file_api_proto_wallet_WithDraw_proto_depIdxs = nil
}
