// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/team/CheckTeamInvite.proto

package team

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//管理员收到询问是否同意邀请用户入群的系统消息事件CheckTeamInvitel,
//做出决定是同意还是不同意邀请用户入群操作
//管理员审核群邀请的请求
type CheckTeamInviteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//群组id
	//是否必须：是
	TeamId string `protobuf:"bytes,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	//邀请人
	//是否必须：是
	Inviter string `protobuf:"bytes,2,opt,name=inviter,proto3" json:"inviter,omitempty"`
	//被邀请人
	//是否必须：是
	Invitee string `protobuf:"bytes,3,opt,name=invitee,proto3" json:"invitee,omitempty"`
	//是否同意邀请用户入群操作
	//true-同意，false-不同意
	//是否必须：是
	IsAgree bool `protobuf:"varint,4,opt,name=isAgree,proto3" json:"isAgree,omitempty"`
	//附加信息
	//是否必须：是
	Msg string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CheckTeamInviteReq) Reset() {
	*x = CheckTeamInviteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_team_CheckTeamInvite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTeamInviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamInviteReq) ProtoMessage() {}

func (x *CheckTeamInviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_team_CheckTeamInvite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamInviteReq.ProtoReflect.Descriptor instead.
func (*CheckTeamInviteReq) Descriptor() ([]byte, []int) {
	return file_api_proto_team_CheckTeamInvite_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTeamInviteReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CheckTeamInviteReq) GetInviter() string {
	if x != nil {
		return x.Inviter
	}
	return ""
}

func (x *CheckTeamInviteReq) GetInvitee() string {
	if x != nil {
		return x.Invitee
	}
	return ""
}

func (x *CheckTeamInviteReq) GetIsAgree() bool {
	if x != nil {
		return x.IsAgree
	}
	return false
}

func (x *CheckTeamInviteReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//管理员审核群邀请的响应
type CheckTeamInviteRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckTeamInviteRsp) Reset() {
	*x = CheckTeamInviteRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_team_CheckTeamInvite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTeamInviteRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamInviteRsp) ProtoMessage() {}

func (x *CheckTeamInviteRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_team_CheckTeamInvite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamInviteRsp.ProtoReflect.Descriptor instead.
func (*CheckTeamInviteRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_team_CheckTeamInvite_proto_rawDescGZIP(), []int{1}
}

var File_api_proto_team_CheckTeamInvite_proto protoreflect.FileDescriptor

var file_api_proto_team_CheckTeamInvite_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x61, 0x6d,
	0x2f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x63, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x73, 0x41, 0x67, 0x72, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x73, 0x41, 0x67, 0x72, 0x65, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x73, 0x70, 0x42, 0x2a,
	0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61,
	0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_proto_team_CheckTeamInvite_proto_rawDescOnce sync.Once
	file_api_proto_team_CheckTeamInvite_proto_rawDescData = file_api_proto_team_CheckTeamInvite_proto_rawDesc
)

func file_api_proto_team_CheckTeamInvite_proto_rawDescGZIP() []byte {
	file_api_proto_team_CheckTeamInvite_proto_rawDescOnce.Do(func() {
		file_api_proto_team_CheckTeamInvite_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_team_CheckTeamInvite_proto_rawDescData)
	})
	return file_api_proto_team_CheckTeamInvite_proto_rawDescData
}

var file_api_proto_team_CheckTeamInvite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_team_CheckTeamInvite_proto_goTypes = []interface{}{
	(*CheckTeamInviteReq)(nil), // 0: cc.lianmi.im.team.CheckTeamInviteReq
	(*CheckTeamInviteRsp)(nil), // 1: cc.lianmi.im.team.CheckTeamInviteRsp
}
var file_api_proto_team_CheckTeamInvite_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_team_CheckTeamInvite_proto_init() }
func file_api_proto_team_CheckTeamInvite_proto_init() {
	if File_api_proto_team_CheckTeamInvite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_team_CheckTeamInvite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTeamInviteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_team_CheckTeamInvite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTeamInviteRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_team_CheckTeamInvite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_team_CheckTeamInvite_proto_goTypes,
		DependencyIndexes: file_api_proto_team_CheckTeamInvite_proto_depIdxs,
		MessageInfos:      file_api_proto_team_CheckTeamInvite_proto_msgTypes,
	}.Build()
	File_api_proto_team_CheckTeamInvite_proto = out.File
	file_api_proto_team_CheckTeamInvite_proto_rawDesc = nil
	file_api_proto_team_CheckTeamInvite_proto_goTypes = nil
	file_api_proto_team_CheckTeamInvite_proto_depIdxs = nil
}
