// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/GetCurrentSeq.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//2.6.19. 获取会话消息序号
//根据会话ID获取单个会话消息序号
type GetCurrentSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//会话ID
	//是否必填-是
	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	//C2C(1) - 点对点通讯
	//C2G(2) - 群组通讯
	//System(3) - 系统消息
	//是否必填-是
	Scene Scene `protobuf:"varint,2,opt,name=scene,proto3,enum=cloud.lianmi.im.msg.Scene" json:"scene,omitempty"`
}

func (x *GetCurrentSeqReq) Reset() {
	*x = GetCurrentSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_GetCurrentSeq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSeqReq) ProtoMessage() {}

func (x *GetCurrentSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_GetCurrentSeq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSeqReq.ProtoReflect.Descriptor instead.
func (*GetCurrentSeqReq) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_GetCurrentSeq_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentSeqReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetCurrentSeqReq) GetScene() Scene {
	if x != nil {
		return x.Scene
	}
	return Scene_Sc_Undefined
}

//2.6.19. 获取会话消息序号
//根据会话ID获取单个会话消息序号
type GetCurrentSeqRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//当前会话读取到的消息id位置
	//默认值“0”
	//是否必填-是
	CurrentMsgId string `protobuf:"bytes,1,opt,name=currentMsgId,proto3" json:"currentMsgId,omitempty"`
	//消息序号，单个会话内自然递增
	//默认值0
	//是否必填-是
	CurrentSeq uint64 `protobuf:"fixed64,2,opt,name=currentSeq,proto3" json:"currentSeq,omitempty"`
}

func (x *GetCurrentSeqRsp) Reset() {
	*x = GetCurrentSeqRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_GetCurrentSeq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentSeqRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSeqRsp) ProtoMessage() {}

func (x *GetCurrentSeqRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_GetCurrentSeq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSeqRsp.ProtoReflect.Descriptor instead.
func (*GetCurrentSeqRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_GetCurrentSeq_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentSeqRsp) GetCurrentMsgId() string {
	if x != nil {
		return x.CurrentMsgId
	}
	return ""
}

func (x *GetCurrentSeqRsp) GetCurrentSeq() uint64 {
	if x != nil {
		return x.CurrentSeq
	}
	return 0
}

var File_api_proto_msg_GetCurrentSeq_proto protoreflect.FileDescriptor

var file_api_proto_msg_GetCurrentSeq_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x62, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x56, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e,
	0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_GetCurrentSeq_proto_rawDescOnce sync.Once
	file_api_proto_msg_GetCurrentSeq_proto_rawDescData = file_api_proto_msg_GetCurrentSeq_proto_rawDesc
)

func file_api_proto_msg_GetCurrentSeq_proto_rawDescGZIP() []byte {
	file_api_proto_msg_GetCurrentSeq_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_GetCurrentSeq_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_GetCurrentSeq_proto_rawDescData)
	})
	return file_api_proto_msg_GetCurrentSeq_proto_rawDescData
}

var file_api_proto_msg_GetCurrentSeq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_msg_GetCurrentSeq_proto_goTypes = []interface{}{
	(*GetCurrentSeqReq)(nil), // 0: cloud.lianmi.im.msg.GetCurrentSeqReq
	(*GetCurrentSeqRsp)(nil), // 1: cloud.lianmi.im.msg.GetCurrentSeqRsp
	(Scene)(0),               // 2: cloud.lianmi.im.msg.Scene
}
var file_api_proto_msg_GetCurrentSeq_proto_depIdxs = []int32{
	2, // 0: cloud.lianmi.im.msg.GetCurrentSeqReq.scene:type_name -> cloud.lianmi.im.msg.Scene
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_msg_GetCurrentSeq_proto_init() }
func file_api_proto_msg_GetCurrentSeq_proto_init() {
	if File_api_proto_msg_GetCurrentSeq_proto != nil {
		return
	}
	file_api_proto_msg_Msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_GetCurrentSeq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_GetCurrentSeq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentSeqRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_GetCurrentSeq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_GetCurrentSeq_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_GetCurrentSeq_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_GetCurrentSeq_proto_msgTypes,
	}.Build()
	File_api_proto_msg_GetCurrentSeq_proto = out.File
	file_api_proto_msg_GetCurrentSeq_proto_rawDesc = nil
	file_api_proto_msg_GetCurrentSeq_proto_goTypes = nil
	file_api_proto_msg_GetCurrentSeq_proto_depIdxs = nil
}
