// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/MessageAttachType.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//消息内容-Image
type AttachImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//图片文件MD5值
	//是否必填-是
	Md5 string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	//图片大小,单位:字节
	//是否必填-是
	Size uint64 `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	//图片宽度
	//是否必填-是
	Width int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	//图片长度
	//是否必填-是
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	//图片访问地址
	//是否必填-是
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	//图片名称
	//是否必填-是
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	//图片类型
	//是否必填-是
	Ext string `protobuf:"bytes,7,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *AttachImage) Reset() {
	*x = AttachImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachImage) ProtoMessage() {}

func (x *AttachImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachImage.ProtoReflect.Descriptor instead.
func (*AttachImage) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_MessageAttachType_proto_rawDescGZIP(), []int{0}
}

func (x *AttachImage) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AttachImage) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttachImage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AttachImage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AttachImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AttachImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttachImage) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

//
//消息内容-Audio
type AttachAudio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//音频文件MD5值
	//是否必填-是
	Md5 string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	//音频大小,单位:字节
	//是否必填-是
	Size uint64 `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	//音频时长,单位:毫秒
	//是否必填-是
	Dur int32 `protobuf:"varint,3,opt,name=dur,proto3" json:"dur,omitempty"`
	//音频访问地址
	//是否必填-是
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	//音频类型
	//是否必填-是
	Ext string `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *AttachAudio) Reset() {
	*x = AttachAudio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachAudio) ProtoMessage() {}

func (x *AttachAudio) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachAudio.ProtoReflect.Descriptor instead.
func (*AttachAudio) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_MessageAttachType_proto_rawDescGZIP(), []int{1}
}

func (x *AttachAudio) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AttachAudio) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttachAudio) GetDur() int32 {
	if x != nil {
		return x.Dur
	}
	return 0
}

func (x *AttachAudio) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AttachAudio) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

//
//消息内容-Video
type AttachVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//视频文件MD5值
	//是否必填-是
	Md5 string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	//视频大小,单位:字节
	//是否必填-是
	Size uint64 `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	//视频时长,单位:毫秒
	//是否必填-是
	Dur int32 `protobuf:"varint,3,opt,name=dur,proto3" json:"dur,omitempty"`
	//视频访问地址
	//是否必填-是
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	//视频预览图
	//是否必填-是
	Preview string `protobuf:"bytes,5,opt,name=preview,proto3" json:"preview,omitempty"`
	//视频类型
	//是否必填-是
	Ext string `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *AttachVideo) Reset() {
	*x = AttachVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachVideo) ProtoMessage() {}

func (x *AttachVideo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachVideo.ProtoReflect.Descriptor instead.
func (*AttachVideo) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_MessageAttachType_proto_rawDescGZIP(), []int{2}
}

func (x *AttachVideo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AttachVideo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttachVideo) GetDur() int32 {
	if x != nil {
		return x.Dur
	}
	return 0
}

func (x *AttachVideo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AttachVideo) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *AttachVideo) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

//
//消息内容-File
type AttachFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//文件MD5值
	//是否必填-是
	Md5 string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	//文件大小,单位:字节
	//是否必填-是
	Size uint64 `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	//文件访问地址
	//是否必填-是
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	//文件类型
	//是否必填-是
	Ext string `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *AttachFile) Reset() {
	*x = AttachFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachFile) ProtoMessage() {}

func (x *AttachFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachFile.ProtoReflect.Descriptor instead.
func (*AttachFile) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_MessageAttachType_proto_rawDescGZIP(), []int{3}
}

func (x *AttachFile) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AttachFile) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttachFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AttachFile) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

//
//消息类型-Geo地理位置
type AttachGeo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//地址信息
	//是否必填-是
	//示例:中国 广东省 广州市 天河区 体育西路167号
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	//纬度
	//是否必填-是
	//示例:23.135917958237425
	Lat float32 `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	//经度
	//是否必填-是
	//示例:113.32090977288983
	Lng float32 `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *AttachGeo) Reset() {
	*x = AttachGeo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachGeo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachGeo) ProtoMessage() {}

func (x *AttachGeo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachGeo.ProtoReflect.Descriptor instead.
func (*AttachGeo) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_MessageAttachType_proto_rawDescGZIP(), []int{4}
}

func (x *AttachGeo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AttachGeo) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *AttachGeo) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type AttachOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO 订单数据 需完善
	OrderData []byte `protobuf:"bytes,1,opt,name=orderData,proto3" json:"orderData,omitempty"`
}

func (x *AttachOrder) Reset() {
	*x = AttachOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachOrder) ProtoMessage() {}

func (x *AttachOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_MessageAttachType_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachOrder.ProtoReflect.Descriptor instead.
func (*AttachOrder) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_MessageAttachType_proto_rawDescGZIP(), []int{5}
}

func (x *AttachOrder) GetOrderData() []byte {
	if x != nil {
		return x.OrderData
	}
	return nil
}

var File_api_proto_msg_MessageAttachType_proto protoreflect.FileDescriptor

var file_api_proto_msg_MessageAttachType_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c,
	0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x22, 0x99, 0x01, 0x0a,
	0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x22, 0x69, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x75, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x78, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x75, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x75, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x22, 0x56, 0x0a, 0x0a, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78,
	0x74, 0x22, 0x49, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x65, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x22, 0x2b, 0x0a, 0x0b,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_MessageAttachType_proto_rawDescOnce sync.Once
	file_api_proto_msg_MessageAttachType_proto_rawDescData = file_api_proto_msg_MessageAttachType_proto_rawDesc
)

func file_api_proto_msg_MessageAttachType_proto_rawDescGZIP() []byte {
	file_api_proto_msg_MessageAttachType_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_MessageAttachType_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_MessageAttachType_proto_rawDescData)
	})
	return file_api_proto_msg_MessageAttachType_proto_rawDescData
}

var file_api_proto_msg_MessageAttachType_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_msg_MessageAttachType_proto_goTypes = []interface{}{
	(*AttachImage)(nil), // 0: cloud.lianmi.im.msg.AttachImage
	(*AttachAudio)(nil), // 1: cloud.lianmi.im.msg.AttachAudio
	(*AttachVideo)(nil), // 2: cloud.lianmi.im.msg.AttachVideo
	(*AttachFile)(nil),  // 3: cloud.lianmi.im.msg.AttachFile
	(*AttachGeo)(nil),   // 4: cloud.lianmi.im.msg.AttachGeo
	(*AttachOrder)(nil), // 5: cloud.lianmi.im.msg.AttachOrder
}
var file_api_proto_msg_MessageAttachType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_msg_MessageAttachType_proto_init() }
func file_api_proto_msg_MessageAttachType_proto_init() {
	if File_api_proto_msg_MessageAttachType_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_MessageAttachType_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_MessageAttachType_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachAudio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_MessageAttachType_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_MessageAttachType_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_MessageAttachType_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachGeo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_MessageAttachType_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_MessageAttachType_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_MessageAttachType_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_MessageAttachType_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_MessageAttachType_proto_msgTypes,
	}.Build()
	File_api_proto_msg_MessageAttachType_proto = out.File
	file_api_proto_msg_MessageAttachType_proto_rawDesc = nil
	file_api_proto_msg_MessageAttachType_proto_goTypes = nil
	file_api_proto_msg_MessageAttachType_proto_depIdxs = nil
}
