// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/ReadMessageHistorys.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//. 拉取历史消息
type ReadMessageHistorysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//会话ID
	//是否必填-是
	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	//读取消息起始消息Id(对应消息结构IdServer字段)
	//是否必填-是
	MaxId string `protobuf:"bytes,2,opt,name=maxId,proto3" json:"maxId,omitempty"`
	//读取消息数量
	//取值范围1～200
	//是否必填-是
	Limit uint32 `protobuf:"fixed32,3,opt,name=limit,proto3" json:"limit,omitempty"`
	//查询方向
	//是否必填-是
	//true 正序，查询比锚点时间更晚的消息
	//false 反序，查询比锚点时间更早的消息
	Direction bool `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *ReadMessageHistorysReq) Reset() {
	*x = ReadMessageHistorysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_ReadMessageHistorys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMessageHistorysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageHistorysReq) ProtoMessage() {}

func (x *ReadMessageHistorysReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_ReadMessageHistorys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageHistorysReq.ProtoReflect.Descriptor instead.
func (*ReadMessageHistorysReq) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_ReadMessageHistorys_proto_rawDescGZIP(), []int{0}
}

func (x *ReadMessageHistorysReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadMessageHistorysReq) GetMaxId() string {
	if x != nil {
		return x.MaxId
	}
	return ""
}

func (x *ReadMessageHistorysReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReadMessageHistorysReq) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

type ReadMessageHistorysRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//消息列表
	//是否必填-是
	Msgs []*MessagePackage `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *ReadMessageHistorysRsp) Reset() {
	*x = ReadMessageHistorysRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_ReadMessageHistorys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMessageHistorysRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageHistorysRsp) ProtoMessage() {}

func (x *ReadMessageHistorysRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_ReadMessageHistorys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageHistorysRsp.ProtoReflect.Descriptor instead.
func (*ReadMessageHistorysRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_ReadMessageHistorys_proto_rawDescGZIP(), []int{1}
}

func (x *ReadMessageHistorysRsp) GetMsgs() []*MessagePackage {
	if x != nil {
		return x.Msgs
	}
	return nil
}

var File_api_proto_msg_ReadMessageHistorys_proto protoreflect.FileDescriptor

var file_api_proto_msg_ReadMessageHistorys_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x1a, 0x22,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x61, 0x78, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x73, 0x52, 0x73, 0x70, 0x12,
	0x37, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_ReadMessageHistorys_proto_rawDescOnce sync.Once
	file_api_proto_msg_ReadMessageHistorys_proto_rawDescData = file_api_proto_msg_ReadMessageHistorys_proto_rawDesc
)

func file_api_proto_msg_ReadMessageHistorys_proto_rawDescGZIP() []byte {
	file_api_proto_msg_ReadMessageHistorys_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_ReadMessageHistorys_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_ReadMessageHistorys_proto_rawDescData)
	})
	return file_api_proto_msg_ReadMessageHistorys_proto_rawDescData
}

var file_api_proto_msg_ReadMessageHistorys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_msg_ReadMessageHistorys_proto_goTypes = []interface{}{
	(*ReadMessageHistorysReq)(nil), // 0: cloud.lianmi.im.msg.ReadMessageHistorysReq
	(*ReadMessageHistorysRsp)(nil), // 1: cloud.lianmi.im.msg.ReadMessageHistorysRsp
	(*MessagePackage)(nil),         // 2: cloud.lianmi.im.msg.MessagePackage
}
var file_api_proto_msg_ReadMessageHistorys_proto_depIdxs = []int32{
	2, // 0: cloud.lianmi.im.msg.ReadMessageHistorysRsp.msgs:type_name -> cloud.lianmi.im.msg.MessagePackage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_msg_ReadMessageHistorys_proto_init() }
func file_api_proto_msg_ReadMessageHistorys_proto_init() {
	if File_api_proto_msg_ReadMessageHistorys_proto != nil {
		return
	}
	file_api_proto_msg_MessagePackage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_ReadMessageHistorys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMessageHistorysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_ReadMessageHistorys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMessageHistorysRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_ReadMessageHistorys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_ReadMessageHistorys_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_ReadMessageHistorys_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_ReadMessageHistorys_proto_msgTypes,
	}.Build()
	File_api_proto_msg_ReadMessageHistorys_proto = out.File
	file_api_proto_msg_ReadMessageHistorys_proto_rawDesc = nil
	file_api_proto_msg_ReadMessageHistorys_proto_goTypes = nil
	file_api_proto_msg_ReadMessageHistorys_proto_depIdxs = nil
}
