// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/RecvMsgEvent.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	auth "github.com/lianmi/servers/api/proto/auth"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//私聊接收消息
//服务器将从from端接收到的消息转发给to端
//api类型-EVENT
type RecvMsgEventRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//传输场景，固定为 C2C或P2P
	//是否必填-是
	Scene MessageScene `protobuf:"varint,1,opt,name=scene,proto3,enum=cloud.lianmi.im.msg.MessageScene" json:"scene,omitempty"`
	//消息类型
	//是否必填-是
	Type MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=cloud.lianmi.im.msg.MessageType" json:"type,omitempty"`
	//接受消息事件的内容 , 更具 type 选择处理方式
	//是否必填-否
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	//消息来源,用户ID
	//是否必填-是
	From string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	//发消息，用户昵称
	//是否必填-是
	FromNick string `protobuf:"bytes,5,opt,name=fromNick,proto3" json:"fromNick,omitempty"`
	//发送方消息设备ID
	//是否必填-是
	FromDeviceId string `protobuf:"bytes,6,opt,name=fromDeviceId,proto3" json:"fromDeviceId,omitempty"`
	//服务器分配的消息ID
	//是否必填-是
	ServerMsgId string `protobuf:"bytes,7,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
	//消息序号，单个会话内自然递增
	//是否必填-是
	Seq uint64 `protobuf:"fixed64,8,opt,name=seq,proto3" json:"seq,omitempty"`
	//客户端分配的消息ID，SDK生成的消息id,
	//在发送消息之后会返回给开发者, 开发者可以在发送消息
	//的结果回调里面根据这个ID来判断相应消息的发送状态,
	//到底是发送成功了还是发送失败了, 然后根据此状态来
	//更新页面的UI。如果发送失败, 那么可以重新发送此消息，推荐UUID
	//是否必填-是
	Uuid string `protobuf:"bytes,9,opt,name=uuid,proto3" json:"uuid,omitempty"`
	//服务器处理消息时间，Unix时间戳
	//是否必填-是
	Time uint64 `protobuf:"fixed64,10,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *RecvMsgEventRsp) Reset() {
	*x = RecvMsgEventRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_RecvMsgEvent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvMsgEventRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvMsgEventRsp) ProtoMessage() {}

func (x *RecvMsgEventRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_RecvMsgEvent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvMsgEventRsp.ProtoReflect.Descriptor instead.
func (*RecvMsgEventRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_RecvMsgEvent_proto_rawDescGZIP(), []int{0}
}

func (x *RecvMsgEventRsp) GetScene() MessageScene {
	if x != nil {
		return x.Scene
	}
	return MessageScene_MsgScene_Undefined
}

func (x *RecvMsgEventRsp) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MsgType_Undefined
}

func (x *RecvMsgEventRsp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RecvMsgEventRsp) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RecvMsgEventRsp) GetFromNick() string {
	if x != nil {
		return x.FromNick
	}
	return ""
}

func (x *RecvMsgEventRsp) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *RecvMsgEventRsp) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *RecvMsgEventRsp) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RecvMsgEventRsp) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RecvMsgEventRsp) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 消息事件 推送是通知的时候 的数据体
type MessageNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//消息来源设备类型,参考登录指令
	//是否必填-是
	FromClientType auth.ClientType `protobuf:"varint,1,opt,name=fromClientType,proto3,enum=cloud.lianmi.im.auth.ClientType" json:"fromClientType,omitempty"`
	//推送通知栏显示内容
	//是否必填-否
	PushContent string `protobuf:"bytes,2,opt,name=pushContent,proto3" json:"pushContent,omitempty"`
	// 通知类型 NOTE 暂定 数字不用枚举
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *MessageNotification) Reset() {
	*x = MessageNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_RecvMsgEvent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNotification) ProtoMessage() {}

func (x *MessageNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_RecvMsgEvent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNotification.ProtoReflect.Descriptor instead.
func (*MessageNotification) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_RecvMsgEvent_proto_rawDescGZIP(), []int{1}
}

func (x *MessageNotification) GetFromClientType() auth.ClientType {
	if x != nil {
		return x.FromClientType
	}
	return auth.ClientType_Ct_UnKnow
}

func (x *MessageNotification) GetPushContent() string {
	if x != nil {
		return x.PushContent
	}
	return ""
}

func (x *MessageNotification) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 系统消息更新 数据体
type MessageSystemUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 系统消息类型
	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	//最后处理人
	//添加好友，对方接收/拒绝后，该字段填充为对方ID
	//申请入群，管理员通过/拒绝后，该字段填充管理员ID
	//邀请入群，用户通过/拒绝后，该字段填充目标用户ID
	//是否必填-否
	HandledAccount string `protobuf:"bytes,2,opt,name=handledAccount,proto3" json:"handledAccount,omitempty"`
	//获取处理者添加的附加信息
	//添加好友，拒绝附言
	//申请入群，拒绝附言
	//邀请入群，拒绝附言
	//是否必填-否
	HandledMsg string `protobuf:"bytes,3,opt,name=handledMsg,proto3" json:"handledMsg,omitempty"`
	// 消息状态 bitset 存储
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 附带的文本 该系统消息的文本
	Text string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	// 最终接受者
	// 管理员可以看到 系统通知 所以管理员有权限修改
	// 所以推送的时候 需要 同时给 管理员推送
	To string `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *MessageSystemUpdate) Reset() {
	*x = MessageSystemUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_RecvMsgEvent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSystemUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSystemUpdate) ProtoMessage() {}

func (x *MessageSystemUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_RecvMsgEvent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSystemUpdate.ProtoReflect.Descriptor instead.
func (*MessageSystemUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_RecvMsgEvent_proto_rawDescGZIP(), []int{2}
}

func (x *MessageSystemUpdate) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MessageSystemUpdate) GetHandledAccount() string {
	if x != nil {
		return x.HandledAccount
	}
	return ""
}

func (x *MessageSystemUpdate) GetHandledMsg() string {
	if x != nil {
		return x.HandledMsg
	}
	return ""
}

func (x *MessageSystemUpdate) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageSystemUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageSystemUpdate) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

var File_api_proto_msg_RecvMsgEvent_proto protoreflect.FileDescriptor

var file_api_proto_msg_RecvMsgEvent_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x13, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69,
	0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x1a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x02, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73,
	0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x20, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e,
	0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x72, 0x6f, 0x6d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x08, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x03, 0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x06, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x95, 0x01, 0x0a,
	0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0e, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e,
	0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x6f, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_RecvMsgEvent_proto_rawDescOnce sync.Once
	file_api_proto_msg_RecvMsgEvent_proto_rawDescData = file_api_proto_msg_RecvMsgEvent_proto_rawDesc
)

func file_api_proto_msg_RecvMsgEvent_proto_rawDescGZIP() []byte {
	file_api_proto_msg_RecvMsgEvent_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_RecvMsgEvent_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_RecvMsgEvent_proto_rawDescData)
	})
	return file_api_proto_msg_RecvMsgEvent_proto_rawDescData
}

var file_api_proto_msg_RecvMsgEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_msg_RecvMsgEvent_proto_goTypes = []interface{}{
	(*RecvMsgEventRsp)(nil),     // 0: cloud.lianmi.im.msg.RecvMsgEventRsp
	(*MessageNotification)(nil), // 1: cloud.lianmi.im.msg.MessageNotification
	(*MessageSystemUpdate)(nil), // 2: cloud.lianmi.im.msg.MessageSystemUpdate
	(MessageScene)(0),           // 3: cloud.lianmi.im.msg.MessageScene
	(MessageType)(0),            // 4: cloud.lianmi.im.msg.MessageType
	(auth.ClientType)(0),        // 5: cloud.lianmi.im.auth.ClientType
}
var file_api_proto_msg_RecvMsgEvent_proto_depIdxs = []int32{
	3, // 0: cloud.lianmi.im.msg.RecvMsgEventRsp.scene:type_name -> cloud.lianmi.im.msg.MessageScene
	4, // 1: cloud.lianmi.im.msg.RecvMsgEventRsp.type:type_name -> cloud.lianmi.im.msg.MessageType
	5, // 2: cloud.lianmi.im.msg.MessageNotification.fromClientType:type_name -> cloud.lianmi.im.auth.ClientType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_msg_RecvMsgEvent_proto_init() }
func file_api_proto_msg_RecvMsgEvent_proto_init() {
	if File_api_proto_msg_RecvMsgEvent_proto != nil {
		return
	}
	file_api_proto_msg_MsgTypeEnum_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_RecvMsgEvent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvMsgEventRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_RecvMsgEvent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_RecvMsgEvent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSystemUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_RecvMsgEvent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_RecvMsgEvent_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_RecvMsgEvent_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_RecvMsgEvent_proto_msgTypes,
	}.Build()
	File_api_proto_msg_RecvMsgEvent_proto = out.File
	file_api_proto_msg_RecvMsgEvent_proto_rawDesc = nil
	file_api_proto_msg_RecvMsgEvent_proto_goTypes = nil
	file_api_proto_msg_RecvMsgEvent_proto_depIdxs = nil
}
