// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/RecvTransparentMsg.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//2.6.27. 接收透传消息
//客户端接收IM服务器转发来的透传消息。
type RecvTransparentMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//消息来源账号或群id
	//是否必填-是
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	//消息来源设备id
	//是否必填-否
	FromDeviceId string `protobuf:"bytes,2,opt,name=fromDeviceId,proto3" json:"fromDeviceId,omitempty"`
	//目标账号或群id
	//是否必填-是
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	//目标设备id
	//是否必填-否
	ToDeviceId string `protobuf:"bytes,4,opt,name=toDeviceId,proto3" json:"toDeviceId,omitempty"`
	//传输场景
	//是否必填-是
	Scene Scene `protobuf:"varint,5,opt,name=scene,proto3,enum=cc.lianmi.im.msg.Scene" json:"scene,omitempty"`
	//客户端自定义命令号
	//是否必填-是
	TransparentCmd int32 `protobuf:"varint,6,opt,name=transparentCmd,proto3" json:"transparentCmd,omitempty"`
	//消息内容，内部结构由客户端自己定义
	//是否必填-是
	Content []byte `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *RecvTransparentMsg) Reset() {
	*x = RecvTransparentMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_RecvTransparentMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvTransparentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvTransparentMsg) ProtoMessage() {}

func (x *RecvTransparentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_RecvTransparentMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvTransparentMsg.ProtoReflect.Descriptor instead.
func (*RecvTransparentMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_RecvTransparentMsg_proto_rawDescGZIP(), []int{0}
}

func (x *RecvTransparentMsg) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RecvTransparentMsg) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *RecvTransparentMsg) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RecvTransparentMsg) GetToDeviceId() string {
	if x != nil {
		return x.ToDeviceId
	}
	return ""
}

func (x *RecvTransparentMsg) GetScene() Scene {
	if x != nil {
		return x.Scene
	}
	return Scene_Sc_Undefined
}

func (x *RecvTransparentMsg) GetTransparentCmd() int32 {
	if x != nil {
		return x.TransparentCmd
	}
	return 0
}

func (x *RecvTransparentMsg) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_api_proto_msg_RecvTransparentMsg_proto protoreflect.FileDescriptor

var file_api_proto_msg_RecvTransparentMsg_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x52, 0x65, 0x63, 0x76, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x63, 0x2e, 0x6c, 0x69, 0x61,
	0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xed, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x76, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x22,
	0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x63, 0x63, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x43, 0x6d, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_RecvTransparentMsg_proto_rawDescOnce sync.Once
	file_api_proto_msg_RecvTransparentMsg_proto_rawDescData = file_api_proto_msg_RecvTransparentMsg_proto_rawDesc
)

func file_api_proto_msg_RecvTransparentMsg_proto_rawDescGZIP() []byte {
	file_api_proto_msg_RecvTransparentMsg_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_RecvTransparentMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_RecvTransparentMsg_proto_rawDescData)
	})
	return file_api_proto_msg_RecvTransparentMsg_proto_rawDescData
}

var file_api_proto_msg_RecvTransparentMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_msg_RecvTransparentMsg_proto_goTypes = []interface{}{
	(*RecvTransparentMsg)(nil), // 0: cc.lianmi.im.msg.RecvTransparentMsg
	(Scene)(0),                 // 1: cc.lianmi.im.msg.Scene
}
var file_api_proto_msg_RecvTransparentMsg_proto_depIdxs = []int32{
	1, // 0: cc.lianmi.im.msg.RecvTransparentMsg.scene:type_name -> cc.lianmi.im.msg.Scene
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_msg_RecvTransparentMsg_proto_init() }
func file_api_proto_msg_RecvTransparentMsg_proto_init() {
	if File_api_proto_msg_RecvTransparentMsg_proto != nil {
		return
	}
	file_api_proto_msg_Msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_RecvTransparentMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvTransparentMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_RecvTransparentMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_RecvTransparentMsg_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_RecvTransparentMsg_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_RecvTransparentMsg_proto_msgTypes,
	}.Build()
	File_api_proto_msg_RecvTransparentMsg_proto = out.File
	file_api_proto_msg_RecvTransparentMsg_proto_rawDesc = nil
	file_api_proto_msg_RecvTransparentMsg_proto_goTypes = nil
	file_api_proto_msg_RecvTransparentMsg_proto_depIdxs = nil
}
