// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/SendCancelMsg.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//撤销消息请求包
type SendCancelMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//被撤销的消息的接收方对应的sessionId
	//完整格式 联系人ID.Scene.设备ID
	//如撤销个人消息 toAccountId.C2C
	//如撤销端对端消息 toAccountId.P2P.toDeviceId
	//如撤销群消息 toTeamId.C2G
	//是否必填-是
	ToSessionId string `protobuf:"bytes,1,opt,name=toSessionId,proto3" json:"toSessionId,omitempty"`
	//要撤销的消息的由服务器分配的消息id
	//是否必填-是
	ServerMsgId string `protobuf:"bytes,2,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
}

func (x *SendCancelMsgReq) Reset() {
	*x = SendCancelMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_SendCancelMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCancelMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCancelMsgReq) ProtoMessage() {}

func (x *SendCancelMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_SendCancelMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCancelMsgReq.ProtoReflect.Descriptor instead.
func (*SendCancelMsgReq) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_SendCancelMsg_proto_rawDescGZIP(), []int{0}
}

func (x *SendCancelMsgReq) GetToSessionId() string {
	if x != nil {
		return x.ToSessionId
	}
	return ""
}

func (x *SendCancelMsgReq) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

type SendCancelMsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendCancelMsgRsp) Reset() {
	*x = SendCancelMsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_SendCancelMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCancelMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCancelMsgRsp) ProtoMessage() {}

func (x *SendCancelMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_SendCancelMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCancelMsgRsp.ProtoReflect.Descriptor instead.
func (*SendCancelMsgRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_SendCancelMsg_proto_rawDescGZIP(), []int{1}
}

var File_api_proto_msg_SendCancelMsg_proto protoreflect.FileDescriptor

var file_api_proto_msg_SendCancelMsg_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x22, 0x56, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x74, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x73,
	0x67, 0x52, 0x73, 0x70, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_SendCancelMsg_proto_rawDescOnce sync.Once
	file_api_proto_msg_SendCancelMsg_proto_rawDescData = file_api_proto_msg_SendCancelMsg_proto_rawDesc
)

func file_api_proto_msg_SendCancelMsg_proto_rawDescGZIP() []byte {
	file_api_proto_msg_SendCancelMsg_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_SendCancelMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_SendCancelMsg_proto_rawDescData)
	})
	return file_api_proto_msg_SendCancelMsg_proto_rawDescData
}

var file_api_proto_msg_SendCancelMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_msg_SendCancelMsg_proto_goTypes = []interface{}{
	(*SendCancelMsgReq)(nil), // 0: cloud.lianmi.im.msg.SendCancelMsgReq
	(*SendCancelMsgRsp)(nil), // 1: cloud.lianmi.im.msg.SendCancelMsgRsp
}
var file_api_proto_msg_SendCancelMsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_msg_SendCancelMsg_proto_init() }
func file_api_proto_msg_SendCancelMsg_proto_init() {
	if File_api_proto_msg_SendCancelMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_SendCancelMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCancelMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_SendCancelMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCancelMsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_SendCancelMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_SendCancelMsg_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_SendCancelMsg_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_SendCancelMsg_proto_msgTypes,
	}.Build()
	File_api_proto_msg_SendCancelMsg_proto = out.File
	file_api_proto_msg_SendCancelMsg_proto_rawDesc = nil
	file_api_proto_msg_SendCancelMsg_proto_goTypes = nil
	file_api_proto_msg_SendCancelMsg_proto_depIdxs = nil
}
