// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/SyncSendTransparentMsg.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//2.6.28. 同步发送透传消息
//多终端环境下，A用户的终端a1发送透传消息，
//通过该协议可以将发送透传消息同步到A的其他终端如a2、a3.
//API类型  EVENT
type SyncSendTransparentMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//目标账号或群id
	//是否必填-是
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	//目标设备id
	//是否必填-否
	ToDeviceId string `protobuf:"bytes,2,opt,name=toDeviceId,proto3" json:"toDeviceId,omitempty"`
	//传输场景
	//是否必填-是
	Scene Scene `protobuf:"varint,3,opt,name=scene,proto3,enum=cloud.lianmi.im.msg.Scene" json:"scene,omitempty"`
	//客户端自定义命令号
	//是否必填-是
	TransparentCmd int32 `protobuf:"varint,4,opt,name=transparentCmd,proto3" json:"transparentCmd,omitempty"`
	//消息内容，内部结构由客户端自己定义
	//是否必填-是
	Content []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SyncSendTransparentMsg) Reset() {
	*x = SyncSendTransparentMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_SyncSendTransparentMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncSendTransparentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSendTransparentMsg) ProtoMessage() {}

func (x *SyncSendTransparentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_SyncSendTransparentMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSendTransparentMsg.ProtoReflect.Descriptor instead.
func (*SyncSendTransparentMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescGZIP(), []int{0}
}

func (x *SyncSendTransparentMsg) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SyncSendTransparentMsg) GetToDeviceId() string {
	if x != nil {
		return x.ToDeviceId
	}
	return ""
}

func (x *SyncSendTransparentMsg) GetScene() Scene {
	if x != nil {
		return x.Scene
	}
	return Scene_Sc_Undefined
}

func (x *SyncSendTransparentMsg) GetTransparentCmd() int32 {
	if x != nil {
		return x.TransparentCmd
	}
	return 0
}

func (x *SyncSendTransparentMsg) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_api_proto_msg_SyncSendTransparentMsg_proto protoreflect.FileDescriptor

var file_api_proto_msg_SyncSendTransparentMsg_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73,
	0x67, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67,
	0x2f, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x53,
	0x79, 0x6e, 0x63, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61,
	0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescOnce sync.Once
	file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescData = file_api_proto_msg_SyncSendTransparentMsg_proto_rawDesc
)

func file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescGZIP() []byte {
	file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescData)
	})
	return file_api_proto_msg_SyncSendTransparentMsg_proto_rawDescData
}

var file_api_proto_msg_SyncSendTransparentMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_msg_SyncSendTransparentMsg_proto_goTypes = []interface{}{
	(*SyncSendTransparentMsg)(nil), // 0: cloud.lianmi.im.msg.SyncSendTransparentMsg
	(Scene)(0),                     // 1: cloud.lianmi.im.msg.Scene
}
var file_api_proto_msg_SyncSendTransparentMsg_proto_depIdxs = []int32{
	1, // 0: cloud.lianmi.im.msg.SyncSendTransparentMsg.scene:type_name -> cloud.lianmi.im.msg.Scene
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_msg_SyncSendTransparentMsg_proto_init() }
func file_api_proto_msg_SyncSendTransparentMsg_proto_init() {
	if File_api_proto_msg_SyncSendTransparentMsg_proto != nil {
		return
	}
	file_api_proto_msg_Msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_SyncSendTransparentMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncSendTransparentMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_SyncSendTransparentMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_SyncSendTransparentMsg_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_SyncSendTransparentMsg_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_SyncSendTransparentMsg_proto_msgTypes,
	}.Build()
	File_api_proto_msg_SyncSendTransparentMsg_proto = out.File
	file_api_proto_msg_SyncSendTransparentMsg_proto_rawDesc = nil
	file_api_proto_msg_SyncSendTransparentMsg_proto_goTypes = nil
	file_api_proto_msg_SyncSendTransparentMsg_proto_depIdxs = nil
}
