// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/SyncSystemMsg.proto

// 用户主从设备之间的消息同步事件

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SystemMsgBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id uint64 `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	// 公告等级
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	// 标题
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	//  内容
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	//Unix时间戳
	CreatedAt uint64 `protobuf:"fixed64,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *SystemMsgBase) Reset() {
	*x = SystemMsgBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_SyncSystemMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMsgBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMsgBase) ProtoMessage() {}

func (x *SystemMsgBase) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_SyncSystemMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMsgBase.ProtoReflect.Descriptor instead.
func (*SystemMsgBase) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_SyncSystemMsg_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMsgBase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SystemMsgBase) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SystemMsgBase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SystemMsgBase) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemMsgBase) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 同步 系统公告  事件
type SyncSystemMsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//系统公告列表
	SystemMsgs []*SystemMsgBase `protobuf:"bytes,1,rep,name=systemMsgs,proto3" json:"systemMsgs,omitempty"`
	//Unix时间戳
	TimeTag uint64 `protobuf:"fixed64,2,opt,name=timeTag,proto3" json:"timeTag,omitempty"`
}

func (x *SyncSystemMsgRsp) Reset() {
	*x = SyncSystemMsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_SyncSystemMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncSystemMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSystemMsgRsp) ProtoMessage() {}

func (x *SyncSystemMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_SyncSystemMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSystemMsgRsp.ProtoReflect.Descriptor instead.
func (*SyncSystemMsgRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_SyncSystemMsg_proto_rawDescGZIP(), []int{1}
}

func (x *SyncSystemMsgRsp) GetSystemMsgs() []*SystemMsgBase {
	if x != nil {
		return x.SystemMsgs
	}
	return nil
}

func (x *SyncSystemMsgRsp) GetTimeTag() uint64 {
	if x != nil {
		return x.TimeTag
	}
	return 0
}

var File_api_proto_msg_SyncSystemMsg_proto protoreflect.FileDescriptor

var file_api_proto_msg_SyncSystemMsg_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x53, 0x79, 0x6e, 0x63, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x22, 0x83, 0x01, 0x0a, 0x0d, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x70,
	0x0a, 0x10, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x52,
	0x73, 0x70, 0x12, 0x42, 0x0a, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c,
	0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x4d, 0x73, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x67,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_SyncSystemMsg_proto_rawDescOnce sync.Once
	file_api_proto_msg_SyncSystemMsg_proto_rawDescData = file_api_proto_msg_SyncSystemMsg_proto_rawDesc
)

func file_api_proto_msg_SyncSystemMsg_proto_rawDescGZIP() []byte {
	file_api_proto_msg_SyncSystemMsg_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_SyncSystemMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_SyncSystemMsg_proto_rawDescData)
	})
	return file_api_proto_msg_SyncSystemMsg_proto_rawDescData
}

var file_api_proto_msg_SyncSystemMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_msg_SyncSystemMsg_proto_goTypes = []interface{}{
	(*SystemMsgBase)(nil),    // 0: cloud.lianmi.im.msg.SystemMsgBase
	(*SyncSystemMsgRsp)(nil), // 1: cloud.lianmi.im.msg.SyncSystemMsgRsp
}
var file_api_proto_msg_SyncSystemMsg_proto_depIdxs = []int32{
	0, // 0: cloud.lianmi.im.msg.SyncSystemMsgRsp.systemMsgs:type_name -> cloud.lianmi.im.msg.SystemMsgBase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_msg_SyncSystemMsg_proto_init() }
func file_api_proto_msg_SyncSystemMsg_proto_init() {
	if File_api_proto_msg_SyncSystemMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_SyncSystemMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMsgBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msg_SyncSystemMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncSystemMsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_SyncSystemMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_SyncSystemMsg_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_SyncSystemMsg_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_SyncSystemMsg_proto_msgTypes,
	}.Build()
	File_api_proto_msg_SyncSystemMsg_proto = out.File
	file_api_proto_msg_SyncSystemMsg_proto_rawDesc = nil
	file_api_proto_msg_SyncSystemMsg_proto_goTypes = nil
	file_api_proto_msg_SyncSystemMsg_proto_depIdxs = nil
}
