// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/SyncUpdateConversationEvent.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//2.6.25. 同步更新会话
//多终端同步更新会话
type SyncUpdateConversationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//会话id,格式为：联系人ID.Scene.设备ID
	//是否必填-是
	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	//供客户端自己扩展使用
	//是否必填-是
	Ext string `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *SyncUpdateConversationEvent) Reset() {
	*x = SyncUpdateConversationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_SyncUpdateConversationEvent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateConversationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateConversationEvent) ProtoMessage() {}

func (x *SyncUpdateConversationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_SyncUpdateConversationEvent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateConversationEvent.ProtoReflect.Descriptor instead.
func (*SyncUpdateConversationEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescGZIP(), []int{0}
}

func (x *SyncUpdateConversationEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SyncUpdateConversationEvent) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

var File_api_proto_msg_SyncUpdateConversationEvent_proto protoreflect.FileDescriptor

var file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x53, 0x79, 0x6e, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x10, 0x63, 0x63, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e,
	0x6d, 0x73, 0x67, 0x22, 0x4d, 0x0a, 0x1b, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65,
	0x78, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescOnce sync.Once
	file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescData = file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDesc
)

func file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescGZIP() []byte {
	file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescData)
	})
	return file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDescData
}

var file_api_proto_msg_SyncUpdateConversationEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_msg_SyncUpdateConversationEvent_proto_goTypes = []interface{}{
	(*SyncUpdateConversationEvent)(nil), // 0: cc.lianmi.im.msg.SyncUpdateConversationEvent
}
var file_api_proto_msg_SyncUpdateConversationEvent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_msg_SyncUpdateConversationEvent_proto_init() }
func file_api_proto_msg_SyncUpdateConversationEvent_proto_init() {
	if File_api_proto_msg_SyncUpdateConversationEvent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_SyncUpdateConversationEvent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateConversationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_SyncUpdateConversationEvent_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_SyncUpdateConversationEvent_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_SyncUpdateConversationEvent_proto_msgTypes,
	}.Build()
	File_api_proto_msg_SyncUpdateConversationEvent_proto = out.File
	file_api_proto_msg_SyncUpdateConversationEvent_proto_rawDesc = nil
	file_api_proto_msg_SyncUpdateConversationEvent_proto_goTypes = nil
	file_api_proto_msg_SyncUpdateConversationEvent_proto_depIdxs = nil
}
