// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/msg/SyncOfflineSysMsgsEvent.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//同步离线期间的系统通知事件
type SyncOfflineSysMsgsEventRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//本次同步，服务器结束时间，unix时间戳，单位ms
	//是否必填-是
	TimeTag uint64 `protobuf:"fixed64,1,opt,name=timeTag,proto3" json:"timeTag,omitempty"`
	//系统通知列表
	//是否必填-是
	// 离线时期的完整消息 ， 可以同步 个人/群/订单/系统事件 ，等
	Messages []*MessagePackage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *SyncOfflineSysMsgsEventRsp) Reset() {
	*x = SyncOfflineSysMsgsEventRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncOfflineSysMsgsEventRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOfflineSysMsgsEventRsp) ProtoMessage() {}

func (x *SyncOfflineSysMsgsEventRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOfflineSysMsgsEventRsp.ProtoReflect.Descriptor instead.
func (*SyncOfflineSysMsgsEventRsp) Descriptor() ([]byte, []int) {
	return file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescGZIP(), []int{0}
}

func (x *SyncOfflineSysMsgsEventRsp) GetTimeTag() uint64 {
	if x != nil {
		return x.TimeTag
	}
	return 0
}

func (x *SyncOfflineSysMsgsEventRsp) GetMessages() []*MessagePackage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_api_proto_msg_SyncOfflineSysMsgsEvent_proto protoreflect.FileDescriptor

var file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x53, 0x79, 0x6e, 0x63, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x79, 0x73, 0x4d, 0x73,
	0x67, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x6d,
	0x73, 0x67, 0x1a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73,
	0x67, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x1a, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x79, 0x73, 0x4d, 0x73, 0x67, 0x73, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x67, 0x12, 0x3f,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e,
	0x69, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69,
	0x61, 0x6e, 0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescOnce sync.Once
	file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescData = file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDesc
)

func file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescGZIP() []byte {
	file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescOnce.Do(func() {
		file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescData)
	})
	return file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDescData
}

var file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_goTypes = []interface{}{
	(*SyncOfflineSysMsgsEventRsp)(nil), // 0: cloud.lianmi.im.msg.SyncOfflineSysMsgsEventRsp
	(*MessagePackage)(nil),             // 1: cloud.lianmi.im.msg.MessagePackage
}
var file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_depIdxs = []int32{
	1, // 0: cloud.lianmi.im.msg.SyncOfflineSysMsgsEventRsp.messages:type_name -> cloud.lianmi.im.msg.MessagePackage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_init() }
func file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_init() {
	if File_api_proto_msg_SyncOfflineSysMsgsEvent_proto != nil {
		return
	}
	file_api_proto_msg_MessagePackage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncOfflineSysMsgsEventRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_goTypes,
		DependencyIndexes: file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_depIdxs,
		MessageInfos:      file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_msgTypes,
	}.Build()
	File_api_proto_msg_SyncOfflineSysMsgsEvent_proto = out.File
	file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_rawDesc = nil
	file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_goTypes = nil
	file_api_proto_msg_SyncOfflineSysMsgsEvent_proto_depIdxs = nil
}
