// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: api/proto/user/SyncUserProfileEvent.proto

package user

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//同步当前用户资料事件
//本指令为事件指令，客户端登录成功后，
//将本地维护端用户资料最后更新时间通过sync同步至服务器端，
//如果服务端用户资料更新时间与本地时间存在差异，
//im服务器则通过该指令将完整用户信息push至客户端。
type SyncUserProfileEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UInfo *User `protobuf:"bytes,1,opt,name=uInfo,proto3" json:"uInfo,omitempty"`
	//最后请求的时间戳
	TimeTag uint64 `protobuf:"fixed64,2,opt,name=timeTag,proto3" json:"timeTag,omitempty"`
}

func (x *SyncUserProfileEvent) Reset() {
	*x = SyncUserProfileEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_user_SyncUserProfileEvent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUserProfileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserProfileEvent) ProtoMessage() {}

func (x *SyncUserProfileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_SyncUserProfileEvent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserProfileEvent.ProtoReflect.Descriptor instead.
func (*SyncUserProfileEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_user_SyncUserProfileEvent_proto_rawDescGZIP(), []int{0}
}

func (x *SyncUserProfileEvent) GetUInfo() *User {
	if x != nil {
		return x.UInfo
	}
	return nil
}

func (x *SyncUserProfileEvent) GetTimeTag() uint64 {
	if x != nil {
		return x.TimeTag
	}
	return 0
}

var File_api_proto_user_SyncUserProfileEvent_proto protoreflect.FileDescriptor

var file_api_proto_user_SyncUserProfileEvent_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2f, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x63, 0x2e,
	0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x1c,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x14,
	0x53, 0x79, 0x6e, 0x63, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x63, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6d, 0x69, 0x2e,
	0x69, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x67, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e,
	0x6d, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_proto_user_SyncUserProfileEvent_proto_rawDescOnce sync.Once
	file_api_proto_user_SyncUserProfileEvent_proto_rawDescData = file_api_proto_user_SyncUserProfileEvent_proto_rawDesc
)

func file_api_proto_user_SyncUserProfileEvent_proto_rawDescGZIP() []byte {
	file_api_proto_user_SyncUserProfileEvent_proto_rawDescOnce.Do(func() {
		file_api_proto_user_SyncUserProfileEvent_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_user_SyncUserProfileEvent_proto_rawDescData)
	})
	return file_api_proto_user_SyncUserProfileEvent_proto_rawDescData
}

var file_api_proto_user_SyncUserProfileEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_user_SyncUserProfileEvent_proto_goTypes = []interface{}{
	(*SyncUserProfileEvent)(nil), // 0: cc.lianmi.im.user.SyncUserProfileEvent
	(*User)(nil),                 // 1: cc.lianmi.im.user.User
}
var file_api_proto_user_SyncUserProfileEvent_proto_depIdxs = []int32{
	1, // 0: cc.lianmi.im.user.SyncUserProfileEvent.uInfo:type_name -> cc.lianmi.im.user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_user_SyncUserProfileEvent_proto_init() }
func file_api_proto_user_SyncUserProfileEvent_proto_init() {
	if File_api_proto_user_SyncUserProfileEvent_proto != nil {
		return
	}
	file_api_proto_user_Account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_user_SyncUserProfileEvent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUserProfileEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_user_SyncUserProfileEvent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_user_SyncUserProfileEvent_proto_goTypes,
		DependencyIndexes: file_api_proto_user_SyncUserProfileEvent_proto_depIdxs,
		MessageInfos:      file_api_proto_user_SyncUserProfileEvent_proto_msgTypes,
	}.Build()
	File_api_proto_user_SyncUserProfileEvent_proto = out.File
	file_api_proto_user_SyncUserProfileEvent_proto_rawDesc = nil
	file_api_proto_user_SyncUserProfileEvent_proto_goTypes = nil
	file_api_proto_user_SyncUserProfileEvent_proto_depIdxs = nil
}
