FROM node:12

WORKDIR /gva_web/
COPY    . .

# https://registry.npm.taobao.org -> https://mirrors.tencentyun.com/npm/ (Tencent cloud internal)
# https://mirrors.cloud.tencent.com/npm/

RUN npm install -g cnpm --registry=https://mirrors.cloud.tencent.com/npm/

RUN cnpm install || npm install \
 && npm run build \
 && mkdir -p /dist \
 && cp -R /gva_web/dist / \
    rm -rf /gva_web