app:
  name: authservice
http:
  mode: release
  port: 28080
  tls: false
db:
  url: lianmidba:12345678@tcp(127.0.0.1:3306)/lianmicloud?charset=utf8&parseTime=True&loc=Local
  debug: false  
nsq:
  broker: 127.0.0.1:4161
  producerAddr: 127.0.0.1:4150
  Topics: Auth.Backend,User.Backend,Friends.Backend,Team.Backend,Sync.Backend
  chnanelName: im
redis:
  addr: 127.0.0.1:6379
  password: 
  db: 0
log:
  filename: /tmp/authservice.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
consul:
  addr: 127.0.0.1:8500
jaeger:
  serviceName: authservice
  reporter:
    localAgentHostPort: "127.0.0.1:6831"
  sampler:
    type: const
    param: 1
