app:
  name: details
http:
  mode: release
  port: 28081
db:
  url: root:12345678@tcp(127.0.0.1:3306)/lianmicloud?charset=utf8&parseTime=True&loc=Local
  debug: false  
log:
  filename: /tmp/details.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
consul:
  addr: 127.0.0.1:8500
grpc:
  port: 0
jaeger:
  serviceName: details
  reporter:
    localAgentHostPort: "127.0.0.1:6831"
  sampler:
    type: const
    param: 1
