app:
  name: dispatcher
http:
  mode: release
  port: 28080
  tls: false
grpc:
  port: 0   
db:
  url: lianmidba:12345678@tcp(127.0.0.1:3306)/lianmicloud?charset=utf8&parseTime=True&loc=Local
  debug: false    
nsq:
  broker: 129.204.153.248:4161
  producerAddr: 129.204.153.248:4150
  topics: Auth.Frontend,User.Frontend,Friends.Frontend,Team.Frontend,Msg.Frontend,Sync.Frontend,Product.Frontend,Order.Frontend,Wallet.Frontend
  chnanelName: im
mqtt:
  addr: 127.0.0.1:1883
  user: ""
  passwd: ""
  clientid: dispatcher-client01
  topicprefix: lianmi/cloud/device/
  responseTopic: lianmi/cloud/dispatcher
  caPath: /root/developments/lianmi/work/basic/mosquitto/ca
redis:
  addr: 127.0.0.1:6379
  password: 
  db: 0
log:
  filename: /tmp/dispatcher.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
consul:
  addr: 127.0.0.1:8500
jaeger:
  serviceName: dispatcher
  reporter:
    localAgentHostPort: "127.0.0.1:6831"
  sampler:
    type: const
    param: 1
