app:
  name: orderservice
http:
  mode: release
  port: 0
db:
  url: lianmidba:12345678@tcp(127.0.0.1:3306)/lianmicloud?charset=utf8&parseTime=True&loc=Local
  debug: false  
nsq:
  broker: 127.0.0.1:4161
  producerAddr: 127.0.0.1:4150
  Topics: Product.Backend,Order.Backend
  chnanelName: im   
redis:
  addr: 127.0.0.1:6379
  password: 
  db: 0
log:
  filename: /tmp/orderservice.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
consul:
  addr: 127.0.0.1:8500
ethereum:
  wsURI: ws://127.0.0.1:8546
  erc20DeployContractAddress: "0x1D2bDDA8954b401fEB52008C63878e698b6B8444"  
jaeger:
  serviceName: orderservice
  reporter:
    localAgentHostPort: "127.0.0.1:6831"
  sampler:
    type: const
    param: 1
